name: Trigger auto deployment for container-app-jsdzsjdvdsl6m

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-jsdzsjdvdsl6m-AutoDeployTrigger-42ca0851-06dd-4051-8656-722f9e9e234a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPJSDZSJDVDSL6M_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPJSDZSJDVDSL6M_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPJSDZSJDVDSL6M_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPJSDZSJDVDSL6M_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPJSDZSJDVDSL6M_REGISTRY_PASSWORD }}
          containerAppName: container-app-jsdzsjdvdsl6m
          resourceGroup: todonodejspgsqlgoogleauth9e3fa9ae
          imageToBuild: default/container-app-jsdzsjdvdsl6m:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


